### ISSUE TITLE
Подсветка клавиш

### ISSUE THREAD

**Issue by shorstok** [shorstok/3k-project#2]
Сделать более гибкую подсветку клавиш. Придумать вариант более заметной подсветки, особенно черных. Возможно, с помощью обводки, может еще как-то. Т.е. нужно сделать и чтоб в глаза бросалось, и чтоб было все равно понятно что это черная или белая клавиша, и желательно чтоб при этом оно визуально приятно выглядело

**Comment by Derrior** [comment]
Можно галочки ставить на использованных клавишах

**Comment by shorstok** [comment]
Галочки как-то так?
![image](https://user-images.githubusercontent.com/17789212/58184443-c6f13000-7cb9-11e9-9bb5-61866e71d1d4.png)

**Comment by Derrior** [comment]
Какие-то такие, да. Это менее естественно, но зато контрастно

**Comment by shorstok** [comment]
Хочется же красивенько, это ж немаловажно, учитывая область применения. Можно галочки заменить на что-то типа кружков с обводкой или треугольников/ромбиков etc. Но мне кажется что и вариант с заливкой и возможно обводкой всей клавиши можно сделать разборчивым и в то же время чтобы он органично смотрелся.

**Comment by shorstok** [comment]
![KEYS_1559293335443](https://user-images.githubusercontent.com/17789212/58694565-f3810800-839b-11e9-8edc-9894f918c7d9.png)

Решил сделать вот такой вариант

f50209bb8b4d6b6400b19d64039166eb3ebb11f7

https://github.com/shorstok/3k-project/tree/keyboard-keys-highlight-accented
